TRAIN TEST SPLIT 
---

* First split is for Training VS Testing
* Second Split is for Stratified K Fold

---
#### required Modules:

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split, StratifiedKFold

randomState = 42

---
#### Import the processed Data

In [9]:
filename = ".\data\processed_data.csv"

data = pd.read_csv(filename)
display(data.head().iloc[:,:15])
display(data.head().iloc[:,15:])
display(data.describe().T)

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,Scr,BUN,FPG,HbA1c,Height
0,63,1,18.3,5,29.1,4.97,5.98,0.831104,2.31,0.97,55,6.6,7,5,140
1,64,0,14.8,4,29.3,3.92,1.77,2.214689,1.44,1.71,50,4.0,11,7,166
2,84,1,60.5,18,29.5,3.97,2.90,1.368966,1.96,0.94,93,8.5,6,6,160
3,53,0,0.2,3,0.3,8.57,4.69,1.827292,4.54,1.74,58,5.0,13,9,173
4,88,1,0.1,4,0.5,4.70,1.30,3.615385,3.29,0.88,120,10.1,7,6,154

,Weight,BMI,Duration,DR,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
0,42,21.428571,27.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,62,22.499637,2.5,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,60,23.437500,9.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,60,20.047446,2.3,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,65,27.407657,3.3,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,count,mean,std,min,25%,50%,75%,max
Age,6380.0,63.835580,7.533908,28.000000,59.000000,64.000000,69.000000,92.000000
Gender,6380.0,0.549373,0.497595,0.000000,0.000000,1.000000,1.000000,1.000000
UAlb,6380.0,49.941082,124.652274,0.100000,5.275000,12.300000,33.200000,1072.200000
Ucr,6380.0,4900.378683,6057.043821,0.000000,7.000000,18.000000,9282.000000,22726.000000
UACR,6380.0,70.932241,1084.392926,0.100000,5.900000,12.100000,33.125000,85427.700000
TC,6380.0,5.347285,1.129842,2.100000,4.620000,5.270000,5.980000,25.000000
TG,6380.0,1.840034,2.162379,0.100000,0.910000,1.370000,2.090000,82.400000
TCTG,6380.0,4.414461,2.656635,0.547380,2.548144,3.810127,5.695255,26.818182
LDLC,6380.0,3.218150,0.951465,0.220000,2.570000,3.190000,3.820000,8.850000
HDLC,6380.0,1.333804,0.312524,0.600000,1.110000,1.290000,1.520000,3.180000
Scr,6380.0,61.686834,20.639001,26.000000,50.000000,59.000000,69.000000,610.000000
BUN,6380.0,5.986160,1.660555,1.600000,4.900000,5.800000,6.800000,23.900000
FPG,6380.0,8.937461,2.656367,4.000000,7.000000,8.000000,10.000000,30.000000
HbA1c,6380.0,7.346238,1.501432,3.000000,6.000000,7.000000,8.000000,14.000000
Height,6380.0,161.557680,7.601245,82.000000,156.000000,161.000000,168.000000,188.000000
Weight,6380.0,64.279467,11.867830,36.000000,58.000000,64.000000,70.000000,564.000000
BMI,6380.0,24.609998,4.447137,15.055139,22.491349,24.221453,26.149277,250.666667
Duration,6380.0,7.818589,5.801607,0.100000,2.700000,6.400000,12.000000,33.000000
DR,6380.0,0.100940,0.301273,0.000000,0.000000,0.000000,0.000000,1.000000
Community_baihe,6380.0,0.116458,0.320798,0.000000,0.000000,0.000000,0.000000,1.000000
Community_chonggu,6380.0,0.070846,0.256588,0.000000,0.000000,0.000000,0.000000,1.000000
Community_huaxin,6380.0,0.109561,0.312366,0.000000,0.000000,0.000000,0.000000,1.000000
Community_jinze,6380.0,0.086834,0.281614,0.000000,0.000000,0.000000,0.000000,1.000000
Community_liantang,6380.0,0.105016,0.306598,0.000000,0.000000,0.000000,0.000000,1.000000
Community_xianghuaqiao,6380.0,0.075549,0.264295,0.000000,0.000000,0.000000,0.000000,1.000000
Community_xujin,6380.0,0.088558,0.284127,0.000000,0.000000,0.000000,0.000000,1.000000
Community_yingpu,6380.0,0.124451,0.330122,0.000000,0.000000,0.000000,0.000000,1.000000
Community_zhaoxian,6380.0,0.106426,0.308407,0.000000,0.000000,0.000000,0.000000,1.000000
Community_zhujiajiao,6380.0,0.116301,0.320611,0.000000,0.000000,0.000000,0.000000,1.000000

In [10]:
X = data.drop(columns=["DR"])
y = pd.DataFrame(data["DR"])

display(X.head().iloc[:,:18])
display(X.head().iloc[:,18:])
display(y.head())

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,Scr,BUN,FPG,HbA1c,Height,Weight,BMI,Duration
0,63,1,18.3,5,29.1,4.97,5.98,0.831104,2.31,0.97,55,6.6,7,5,140,42,21.428571,27.0
1,64,0,14.8,4,29.3,3.92,1.77,2.214689,1.44,1.71,50,4.0,11,7,166,62,22.499637,2.5
2,84,1,60.5,18,29.5,3.97,2.90,1.368966,1.96,0.94,93,8.5,6,6,160,60,23.437500,9.0
3,53,0,0.2,3,0.3,8.57,4.69,1.827292,4.54,1.74,58,5.0,13,9,173,60,20.047446,2.3
4,88,1,0.1,4,0.5,4.70,1.30,3.615385,3.29,0.88,120,10.1,7,6,154,65,27.407657,3.3

,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

   DR
0   0
1   0
2   0
3   0
4   0

---
#### First Split

In [ ]:
X_kfold, X_test, y_kfold, y_test = train_test_split(X, y, test_size=0.1, random_state=randomState,stratify=y)
display(X_kfold)

<class 'pandas.core.frame.DataFrame'>

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,65,0,0.1,8,0.1,3.94,0.60,6.566667,2.01,1.57,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1695,54,0,26.5,9,25.0,4.62,5.82,0.793814,1.77,0.80,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4730,76,1,64.2,9851,57.7,6.04,1.54,3.922078,3.57,1.78,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1051,61,0,171.3,18,82.8,5.12,1.38,3.710145,3.68,1.15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1325,54,1,5.0,11,3.9,5.92,0.65,9.107692,3.79,1.59,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

---
#### Stratified K Fold

In [ ]:
kF = StratifiedKFold(n_splits=5,shuffle=True, random_state=randomState)

kFold = []

for fold, (train_idx, test_idx) in enumerate(kF.split(X_kfold,y_kfold)):
    # print(f"Fold: {fold}", train_idx, test_idx)
    # print(f"Frame: {fold}", X_kfold.shape, y_kfold.shape)
    train_x, train_y = X_kfold.iloc[train_idx], y_kfold.iloc[train_idx]
    test_x, test_y = X_kfold.iloc[test_idx], y_kfold.iloc[test_idx]
    # print(f"Fold: {fold}")
    # print(f"Train: {train_x.shape}, {train_y.shape}")
    # print(f"Test: {test_x.shape}, {test_y.shape}")
    kFold.append((train_x, test_x, train_y, test_y))
    
#? whatever is in this kFold list are still pandas DataFrames

Fold: 0 [   0    1    2 ... 5737 5739 5740] [   6   23   26 ... 5732 5738 5741]
Frame: 0 (5742, 28) (5742, 1)
Train: (4593, 28), (4593, 1)
Test: (1149, 28), (1149, 1)
Fold: 1 [   2    4    5 ... 5739 5740 5741] [   0    1    3 ... 5718 5726 5731]
Frame: 1 (5742, 28) (5742, 1)
Train: (4593, 28), (4593, 1)
Test: (1149, 28), (1149, 1)
Fold: 2 [   0    1    2 ... 5738 5740 5741] [   8   24   29 ... 5729 5733 5739]
Frame: 2 (5742, 28) (5742, 1)
Train: (4594, 28), (4594, 1)
Test: (1148, 28), (1148, 1)
Fold: 3 [   0    1    2 ... 5738 5739 5741] [   4   10   12 ... 5734 5735 5740]
Frame: 3 (5742, 28) (5742, 1)
Train: (4594, 28), (4594, 1)
Test: (1148, 28), (1148, 1)
Fold: 4 [   0    1    3 ... 5739 5740 5741] [   2    5    9 ... 5727 5736 5737]
Frame: 4 (5742, 28) (5742, 1)
Train: (4594, 28), (4594, 1)
Test: (1148, 28), (1148, 1)

In [ ]:
# for fold, items in enumerate(kFold,start=1):
#     print(f"Fold: {fold} ")
#     string = "  "
#     for item in items:
#         display(item.head())

Fold: 1

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
348,72,1,19.9,4,37.3,3.89,1.39,2.798561,2.45,0.92,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2608,59,0,0.7,10,0.6,6.32,6.13,1.030995,2.77,1.13,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5711,65,1,3.8,8607,3.9,5.97,1.54,3.876623,3.57,1.61,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6164,62,0,16.1,6609,21.6,6.22,2.54,2.448819,3.92,1.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5338,73,1,60.7,20813,25.8,4.09,1.21,3.380165,2.44,1.15,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

      DR
591    0
3572   0
3384   0
1300   0
269    0

      DR
348    0
2608   0
5711   0
6164   0
5338   0

Fold: 2

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1619,70,0,31.0,17,16.1,7.22,1.91,3.780105,5.00,1.54,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,72,1,19.9,4,37.3,3.89,1.39,2.798561,2.45,0.92,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5014,74,0,17.2,19701,7.7,5.27,0.83,6.349398,3.21,1.55,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,50,1,4.1,6,5.2,5.64,1.49,3.785235,3.71,1.21,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1433,52,0,4.8,6,6.3,3.49,0.36,9.694444,2.03,1.23,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

      DR
3384   0
269    0
1619   0
348    0
5014   0

      DR
591    0
3572   0
1300   0
79     0
1433   0

Fold: 3

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
5014,74,0,17.2,19701,7.7,5.27,0.83,6.349398,3.21,1.55,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4288,69,1,2.1,6930,2.7,5.52,2.81,1.964413,3.36,1.04,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1601,76,1,5.0,3,14.4,6.50,2.29,2.838428,4.35,1.46,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2561,48,0,1006.0,15,579.4,5.64,1.33,4.240602,3.74,1.27,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5888,60,1,4.7,5,7.9,5.67,0.81,7.000000,3.61,1.50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

      DR
591    0
3572   0
3384   0
1300   0
269    0

      DR
5014   0
4288   0
1601   0
2561   1
5888   0

Fold: 4

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1619,70,0,31.0,17,16.1,7.22,1.91,3.780105,5.00,1.54,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5428,70,1,36.9,7504,43.5,4.34,2.34,1.854701,1.97,1.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5967,64,1,1.4,1228,10.1,4.42,1.20,3.683333,3.05,0.89,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5084,67,1,11.2,10259,9.7,6.81,0.56,12.160714,4.09,1.98,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5112,57,0,23.1,18861,10.8,4.20,1.37,3.065693,2.86,1.03,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

      DR
591    0
3572   0
3384   0
1300   0
1619   0

      DR
269    0
5428   0
5967   0
5084   0
5112   0

Fold: 5

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
591,62,1,4.8,8,4.8,5.63,1.06,5.311321,4.06,1.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3572,74,0,21.8,11481,16.8,5.40,0.55,9.818182,4.18,1.36,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1300,66,0,3.4,8,3.4,4.90,0.92,5.326087,3.03,1.31,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
269,36,0,21.2,11,16.9,5.85,3.76,1.555851,2.71,1.06,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
348,72,1,19.9,4,37.3,3.89,1.39,2.798561,2.45,0.92,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

,Age,Gender,UAlb,Ucr,UACR,TC,TG,TCTG,LDLC,HDLC,...,Community_baihe,Community_chonggu,Community_huaxin,Community_jinze,Community_liantang,Community_xianghuaqiao,Community_xujin,Community_yingpu,Community_zhaoxian,Community_zhujiajiao
3384,71,1,7.3,8990,7.2,6.11,1.51,4.046358,4.30,1.22,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1619,70,0,31.0,17,16.1,7.22,1.91,3.780105,5.00,1.54,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3118,60,0,28.3,4,52.4,4.80,2.74,1.751825,2.56,1.08,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1662,64,1,3.0,1,20.7,5.13,2.73,1.879121,2.98,1.39,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5939,77,0,11.3,10828,9.2,6.12,2.02,3.029703,4.03,1.59,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

      DR
591    0
3572   0
1300   0
269    0
348    0

      DR
3384   0
1619   0
3118   0
1662   0
5939   0

Testing Py imports
---

In [ ]:
from modularModels1 import BlockMaker, modularNN
import torch
import torch.nn as nn
import torch.nn.init as init

model_1 = modularNN(1,
                   blocks=[BlockMaker(28,[128,128],64,
                                      [nn.ReLU(),nn.ReLU(),nn.LeakyReLU()]),
                           BlockMaker(64,[64],32,
                                      [(nn.ELU(),nn.Dropout(0.2)),nn.Sigmoid()]),
                           ],
                   blockSize=(28,32))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print(device)
model_1 = model_1.to(device)
print(model_1)

#? Initializer: Xavier Normal Distribution
for layer in model_1.modules():
    if isinstance(layer, (nn.Linear, nn.Conv2d)):  # Check if the layer has weights
        init.xavier_normal_(layer.weight)  # Initialize weights using Xavier Normal
        if layer.bias is not None:
            init.normal_(layer.bias, mean=0, std=0.05)

A modularNN(
  (layers): Sequential(
    (0): BlockMaker(
      (layers): Sequential(
        (0): Linear(in_features=28, out_features=128, bias=True)
        (1): ReLU()
        (2): Linear(in_features=128, out_features=128, bias=True)
        (3): ReLU()
        (4): Linear(in_features=128, out_features=64, bias=True)
        (5): LeakyReLU(negative_slope=0.01)
      )
    )
    (1): BlockMaker(
      (layers): Sequential(
        (0): Linear(in_features=64, out_features=64, bias=True)
        (1): ELU(alpha=1.0)
        (2): Dropout(p=0.2, inplace=False)
        (3): Linear(in_features=64, out_features=32, bias=True)
        (4): Sigmoid()
      )
    )
    (2): Linear(in_features=32, out_features=1, bias=True)
  )
)
layers.0.layers.0.weight Parameter containing:
tensor([[-0.0079,  0.0174,  0.0388,  ...,  0.2925, -0.0374,  0.0264],
        [ 0.0856,  0.1323, -0.0089,  ..., -0.0334,  0.0303, -0.0457],
        [ 0.0547, -0.0182, -0.0952,  ..., -0.1509, -0.2156, -0.2254],
        ...,
        [-0.0995,  0.0803, -0.0107,  ..., -0.1459,  0.0091, -0.0419],
        [ 0.2134,  0.1376,  0.1387,  ...,  0.1070, -0.1087, -0.0007],
        [ 0.0394,  0.0508, -0.1346,  ..., -0.1819,  0.0365, -0.0396]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.0.layers.0.bias Parameter containing:
tensor([ 0.0682,  0.0538, -0.0273, -0.0032,  0.0423, -0.0296, -0.0102,  0.0314,
        -0.0299, -0.0201, -0.0946, -0.0167, -0.0581,  0.0136,  0.0284,  0.0516,
        -0.0271,  0.0215, -0.0107, -0.0423, -0.0626,  0.0156,  0.1047, -0.0175,
         0.0144,  0.0489, -0.1065, -0.0349,  0.0860, -0.0067,  0.0414, -0.0068,
        -0.0359,  0.0106, -0.0417,  0.0915, -0.0039, -0.0176,  0.0012, -0.0385,
         0.0214, -0.0096,  0.0426, -0.0571,  0.0290, -0.0661, -0.0355,  0.0220,
        -0.0715,  0.0241,  0.0271,  0.0161,  0.0591, -0.0421, -0.0493,  0.0477,
         0.0267,  0.0135, -0.0101, -0.0492, -0.0215,  0.0211,  0.0264,  0.0664,
         0.0012,  0.0515,  0.0189,  0.0077,  0.0376,  0.0226,  0.0479,  0.0288,
         0.0419,  0.0112,  0.0740,  0.0622, -0.0839,  0.0238,  0.0629, -0.0360,
        -0.0744,  0.0071,  0.0387,  0.0308, -0.0406,  0.0491, -0.0034, -0.0997,
        -0.0516, -0.0556,  0.0161, -0.0314, -0.1232, -0.0265, -0.0793,  0.0171,
         0.0694,  0.0270,  0.0307, -0.0338,  0.0508, -0.0247,  0.0090, -0.0206,
        -0.0304,  0.0194, -0.0859,  0.1523,  0.0720,  0.0758,  0.0406,  0.0507,
        -0.1185,  0.0867, -0.0599,  0.0794, -0.0131, -0.0476,  0.0304, -0.0131,
         0.0415, -0.0072,  0.0283, -0.0359, -0.0139,  0.0450, -0.1021,  0.0099],
       device='cuda:0', requires_grad=True)
torch.float32
layers.0.layers.2.weight Parameter containing:
tensor([[ 0.0906, -0.0613,  0.0200,  ...,  0.0982,  0.0133,  0.2799],
        [-0.0584,  0.0540,  0.0278,  ...,  0.0740, -0.1126,  0.1082],
        [ 0.1047, -0.0005,  0.0681,  ...,  0.2025, -0.1194, -0.0606],
        ...,
        [ 0.0586, -0.1212,  0.0384,  ...,  0.0278,  0.1399, -0.1181],
        [ 0.0284, -0.0099,  0.0815,  ...,  0.0444,  0.0709, -0.0818],
        [-0.1338, -0.1014, -0.0738,  ...,  0.0320,  0.0754, -0.0657]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.0.layers.2.bias Parameter containing:
tensor([ 0.1215,  0.0871, -0.0049,  0.0352, -0.0446, -0.0414, -0.0985, -0.0058,
        -0.0667,  0.0158,  0.0402,  0.0098,  0.0266,  0.0057,  0.0397,  0.0962,
         0.1066, -0.0406,  0.0441, -0.0049, -0.0427, -0.0429, -0.0260,  0.0017,
         0.0191,  0.0280, -0.0626, -0.0558,  0.0829,  0.0063, -0.0165, -0.0047,
         0.1020, -0.0848,  0.0622,  0.0055, -0.0720,  0.0204, -0.0133,  0.0786,
        -0.0406,  0.0027, -0.0025,  0.0016, -0.0272, -0.0276, -0.0431,  0.0336,
        -0.0310,  0.0566, -0.0129, -0.0171, -0.0270,  0.0621, -0.0186, -0.0337,
        -0.0754,  0.0458, -0.0360, -0.0326,  0.0455, -0.0467, -0.0067,  0.0015,
         0.0173, -0.0644,  0.0693,  0.0154, -0.0228, -0.0317,  0.0575, -0.0020,
        -0.0399, -0.0820,  0.0962, -0.0275,  0.0395,  0.0739, -0.0601,  0.0144,
        -0.0938,  0.0261, -0.0058, -0.0663,  0.0726,  0.0876,  0.0312, -0.0328,
        -0.0234, -0.0007,  0.0147,  0.0717,  0.0104,  0.0145,  0.0078,  0.1193,
        -0.0495,  0.0072,  0.0342, -0.0601, -0.0249, -0.0198, -0.0178, -0.0649,
        -0.0152,  0.0011,  0.0615, -0.0404, -0.0028,  0.0338,  0.0439, -0.0437,
        -0.0241,  0.0369,  0.0240,  0.0188, -0.0566, -0.0008, -0.0080,  0.0362,
        -0.0858, -0.0143, -0.0543, -0.0597, -0.0233,  0.0850, -0.0592,  0.0348],
       device='cuda:0', requires_grad=True)
torch.float32
layers.0.layers.4.weight Parameter containing:
tensor([[-0.1147,  0.3394, -0.0533,  ...,  0.0678, -0.0603, -0.0510],
        [-0.2038,  0.0490,  0.1006,  ...,  0.0629, -0.1414, -0.0898],
        [ 0.1369,  0.0849,  0.1392,  ...,  0.0197,  0.0583, -0.0598],
        ...,
        [-0.0279,  0.0029,  0.0568,  ..., -0.0908, -0.0411, -0.1622],
        [ 0.0143,  0.1556, -0.0638,  ...,  0.1320, -0.0643,  0.0310],
        [-0.0611, -0.0893,  0.1922,  ...,  0.0148,  0.0513,  0.0694]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.0.layers.4.bias Parameter containing:
tensor([ 4.5939e-02, -2.8609e-02, -3.7587e-02, -2.1957e-02, -8.8378e-05,
        -6.9064e-02, -3.1196e-02, -2.7063e-02, -3.5729e-02,  5.8033e-03,
         3.0330e-03,  3.5417e-03, -6.4374e-03,  1.0559e-02, -2.1697e-02,
        -1.5804e-02, -4.5290e-02,  1.0606e-02, -2.8816e-02, -1.0353e-02,
         3.7151e-02,  2.5485e-02,  8.1950e-02, -4.1274e-02, -3.9313e-03,
         2.8552e-02,  6.9288e-02, -9.6683e-02, -2.4326e-02, -5.0909e-02,
        -4.6772e-02,  7.8163e-03,  7.8222e-02, -6.7811e-02, -3.5398e-02,
        -4.1871e-02, -7.4896e-03,  4.3731e-02,  8.2257e-02,  4.0475e-02,
        -5.1885e-02,  5.0858e-03, -4.2648e-03, -3.6371e-02,  1.1228e-02,
         3.8597e-02, -5.4762e-02,  1.1493e-01, -7.5532e-02,  2.1932e-02,
         3.1945e-02,  9.8471e-04,  3.5876e-03,  5.1873e-03,  3.3333e-02,
         2.7238e-02, -6.2764e-02, -6.0003e-03,  1.4868e-02,  2.4322e-02,
        -5.5418e-02, -5.4371e-02, -8.2628e-02,  4.6035e-02], device='cuda:0',
       requires_grad=True)
torch.float32
layers.1.layers.0.weight Parameter containing:
tensor([[ 0.0994, -0.2407,  0.0198,  ..., -0.0924,  0.1228,  0.1737],
        [-0.0565,  0.0793,  0.2125,  ...,  0.0491, -0.1594,  0.0122],
        [ 0.1987,  0.2100, -0.0597,  ...,  0.0682,  0.0945,  0.0038],
        ...,
        [-0.0073, -0.1793,  0.1849,  ...,  0.2080,  0.0460, -0.0538],
        [-0.0875, -0.0554, -0.0315,  ...,  0.0541, -0.0348,  0.0072],
        [ 0.2555, -0.0711, -0.1097,  ..., -0.1366, -0.1605,  0.1704]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.1.layers.0.bias Parameter containing:
tensor([-0.1255,  0.0648,  0.0336, -0.0512, -0.0071,  0.0328,  0.0653, -0.0301,
        -0.0775,  0.0541, -0.0656, -0.0796, -0.0344, -0.0756,  0.0192, -0.0051,
        -0.0143, -0.0102, -0.0349,  0.0293,  0.1235, -0.0282, -0.0385, -0.0098,
         0.0413,  0.0875, -0.0201, -0.0642, -0.0809,  0.0699, -0.0653,  0.0188,
        -0.0925,  0.0285,  0.0272,  0.0130,  0.0080, -0.0443, -0.0152,  0.0953,
         0.0640, -0.0361,  0.0454, -0.0091, -0.0592,  0.0846,  0.0232,  0.0594,
        -0.0926,  0.0162,  0.0365, -0.0352,  0.1228, -0.0805,  0.0576, -0.0840,
        -0.0205, -0.0685,  0.0181, -0.0281, -0.0263, -0.0833, -0.0767, -0.0620],
       device='cuda:0', requires_grad=True)
torch.float32
layers.1.layers.3.weight Parameter containing:
tensor([[-0.0319,  0.2597,  0.1338,  ...,  0.1242,  0.0363, -0.4006],
        [-0.0391, -0.2016,  0.0597,  ...,  0.0081, -0.1185,  0.2006],
        [ 0.2006,  0.2391,  0.1666,  ..., -0.1509, -0.1192, -0.2978],
        ...,
        [ 0.0026,  0.1850, -0.2732,  ...,  0.0446,  0.1364,  0.1145],
        [-0.1316, -0.1190, -0.1365,  ..., -0.0263, -0.2338,  0.1655],
        [-0.0332, -0.0032,  0.0444,  ...,  0.2269, -0.0013, -0.1017]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.1.layers.3.bias Parameter containing:
tensor([-0.0193, -0.0595, -0.0550, -0.0481,  0.0915,  0.0609, -0.0259, -0.0612,
        -0.0153,  0.0508,  0.0361, -0.0621,  0.0115,  0.0267, -0.0086, -0.0250,
         0.0027, -0.0347, -0.0827, -0.0172,  0.0095,  0.0082,  0.0001, -0.0634,
        -0.0612,  0.0573, -0.0008,  0.0131, -0.0328,  0.1066,  0.0780,  0.0381],
       device='cuda:0', requires_grad=True)
torch.float32
layers.2.weight Parameter containing:
tensor([[-0.5741, -0.0531, -0.1918, -0.0995,  0.0423, -0.2754,  0.3544, -0.4927,
         -0.0725, -0.5868, -0.2744,  0.3453, -0.0731,  0.1650, -0.2015, -0.2124,
         -0.0044, -0.1964, -0.2544,  0.1631,  0.4577, -0.0456, -0.2964, -0.0071,
         -0.3322,  0.0133,  0.1785,  0.0852, -0.3259, -0.2305, -0.5599, -0.0560]],
       device='cuda:0', requires_grad=True)
torch.float32
layers.2.bias Parameter containing:
tensor([-0.0655], device='cuda:0', requires_grad=True)
torch.float32

In [ ]:
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import recall_score
epochs = 5
batchSize = 64
criterion = nn.BCELoss()
optimiser = optim.Adam(model_1.parameters(),lr=0.01)


for fold, (train_x, test_x, train_y, test_y) in enumerate(kFold):

    #? Need to convert the pd.DataFrames to torch.tensors
    # train_x = torch.tensor(train_x.values,dtype=torch.float32)
    # train_y = torch.tensor(train_y.values,dtype=torch.float32)
    # test_x = torch.tensor(test_x.values,dtype=torch.float32) 
    # test_y = torch.tensor(test_y.values,dtype=torch.float32)

    train_dataset = TensorDataset(torch.tensor(train_x.values,dtype=torch.float32), torch.tensor(train_y.values,dtype=torch.float32))
    test_dataset = TensorDataset(torch.tensor(test_x.values,dtype=torch.float32), torch.tensor(test_y.values,dtype=torch.float32))

    train_loader = DataLoader(train_dataset, batch_size=batchSize, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batchSize, shuffle=False)

    model_1.train()
    print(f"Fold: {fold+1}")
    for epoch in range(epochs):
        running_loss = 0.0
        correct_train = 0
        total_train = 0

        for batch, (inputs, labels) in enumerate(train_loader):
            print("inputs:",inputs)
            # print("labels:",labels)
            inputs, labels = inputs.to(device), labels.to(device).squeeze()
            optimiser.zero_grad()
            outputs = model_1(inputs).squeeze()
            print(outputs)
            # print("Labels",labels)
            loss = criterion(outputs, labels)
            loss.backward()
            optimiser.step()

            running_loss += loss.item()
            predicted = (torch.sigmoid(outputs) > 0.5).float()
            labels2 = labels.cpu()
            correct_train += (predicted == labels).sum().item()
            total_train += labels.size(0)
            recallScore = recall_score(labels2,predicted.cpu())

            print(f" Epoch [{epoch+1}/{epochs}]".ljust(10),
                  f"Batch: {batch+1}".ljust(10),
                  f"Loss: {running_loss/batchSize/(batch+1)}".ljust(12),
                  f"RecallScore: {(recallScore):.3f}", end="\r")
            break

        train_accuracy = 100 * correct_train / total_train
        avg_loss = running_loss / len(train_loader)

        print(f" Epoch [{epoch+1}/{epochs}]".ljust(10),
              f"Loss: {avg_loss:.4f}".ljust(12),
              f"Accuracy: {train_accuracy:.2f}%".ljust(30))
        break



# model_1.eval()
# correct = 0
# total = 0
# with torch.no_grad():
#     for inputs, labels in test_loader:
#         inputs, labels = inputs.to(device), labels.float().to(device).squeeze()
#         outputs = model_1(inputs).squeeze()
#         predicted = (torch.sigmoid(outputs) > 0.5).float()
#         total += labels.size(0)
#         correct += (predicted == labels).sum().item()

# val_accuracy = (correct / total)*100
# print(f"val acc: {val_accuracy:.2f}%\n")

Fold: 1
tensor([-1.2384, -1.0945, -1.3340, -0.4501, -0.8281, -1.2066, -1.7597, -1.6774,
        -0.9931, -1.2461, -1.8297, -1.0964, -1.6878, -0.1708, -2.1059, -2.0986,
        -0.4986, -1.1712, -1.9771, -1.7967, -2.3172, -1.3463, -1.3800, -0.7058,
        -0.9022, -1.0224, -1.5575, -2.0584, -0.4936, -1.9406, -1.0826, -1.7401,
        -1.7821, -0.8979, -1.2316, -1.4998, -1.5885, -1.6514, -1.3735, -1.8608,
        -1.2533, -1.5491, -1.4731, -2.0064, -1.4167, -0.9186, -1.0216, -1.2118,
        -0.8958, -0.2610, -1.1807, -1.1939, -1.4300, -1.3358, -1.3174, -1.7311,
        -1.1367, -0.6763, -1.2016, -0.9955, -1.1394, -0.7992, -1.5009, -1.8208],
       device='cuda:0', grad_fn=<SqueezeBackward0>)

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.